// <auto-generated />
using System;
using Bookish.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bookish.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210321030545_AddedPostedBy")]
    partial class AddedPostedBy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Bookish.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Commented_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Commented_ById")
                        .HasColumnType("integer");

                    b.Property<int>("Commented_OnId")
                        .HasColumnType("integer");

                    b.Property<int?>("Commented_UnderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Commented_ById");

                    b.HasIndex("Commented_OnId");

                    b.HasIndex("Commented_UnderId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Bookish.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Posted_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Posted_ById")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Posted_ById");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Bookish.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bookish.Data.Comment", b =>
                {
                    b.HasOne("Bookish.Data.User", "Commented_By")
                        .WithMany()
                        .HasForeignKey("Commented_ById");

                    b.HasOne("Bookish.Data.Post", "Commented_On")
                        .WithMany("Comments")
                        .HasForeignKey("Commented_OnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookish.Data.Comment", "Commented_Under")
                        .WithMany()
                        .HasForeignKey("Commented_UnderId");
                });

            modelBuilder.Entity("Bookish.Data.Post", b =>
                {
                    b.HasOne("Bookish.Data.User", "Posted_By")
                        .WithMany()
                        .HasForeignKey("Posted_ById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
