// <auto-generated />
using System;
using Bookish.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bookish.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Bookish.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Commented_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Commented_UnderId")
                        .HasColumnType("integer");

                    b.Property<int?>("Commneted_OnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Commented_UnderId");

                    b.HasIndex("Commneted_OnId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Bookish.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Posted_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Bookish.Data.Comment", b =>
                {
                    b.HasOne("Bookish.Data.Comment", "Commented_Under")
                        .WithMany()
                        .HasForeignKey("Commented_UnderId");

                    b.HasOne("Bookish.Data.Post", "Commneted_On")
                        .WithMany("Comments")
                        .HasForeignKey("Commneted_OnId");
                });
#pragma warning restore 612, 618
        }
    }
}
